GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json


###
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "The 7 Habits of Highly Effective People"
}

###
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "The Power of Positive Thinking"
}

###
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json
